### ISSUE TITLE
Propably wrong colors for embed messages

### ISSUE THREAD

**Issue by GorlikItsMe** [Ninjaclasher/django-discord-integration#2]
Hi I notice there are probably wrong color codes for messages
Error is red
Warning is orange
but Info is Yellow

What do you think to add to settings opportunity to change default color settings?

**Comment by GorlikItsMe** [comment]
I make PR with this changes https://github.com/Ninjaclasher/django-discord-integration/pull/3

**Comment by Ninjaclasher** [comment]
Resolved by #3.

**Comment by GorlikItsMe** [comment]
could you bump version?

**Comment by Ninjaclasher** [comment]
Done.
